def throw_exception():
    raise ArithmeticError("Exception thrown from method")

throw_exception()  # No try-except, program will terminate
